"""init tables

Revision ID: d551d1b6a9d8
Revises: 
Create Date: 2026-05-18 19:56:51.867350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd551d1b6a9d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS info_api")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('middlename', sa.String(length=255), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('license_serial', sa.String(length=20), nullable=False),
    sa.Column('license_number', sa.String(length=20), nullable=False),
    sa.Column('license_issue_date', sa.Date(), nullable=False),
    sa.Column('license_exp_date', sa.Date(), nullable=False),
    sa.Column('licence_foreign', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('kbm', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='info_api'
    )
    op.create_table('insurance_companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('commission_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('koef', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='info_api'
    )
    op.create_table('persons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('middlename', sa.String(length=255), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('passport_serial', sa.String(length=255), nullable=False),
    sa.Column('passport_number', sa.String(length=255), nullable=False),
    sa.Column('passport_issue_date', sa.Date(), nullable=False),
    sa.Column('passport_issuer', sa.String(length=255), nullable=False),
    sa.Column('passport_code', sa.String(length=255), nullable=False),
    sa.Column('passport_foreign', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='info_api'
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('license_plate', sa.String(), nullable=False),
    sa.Column('vin', sa.String(), nullable=True),
    sa.Column('body_number', sa.String(), nullable=True),
    sa.Column('chassis_number', sa.String(), nullable=True),
    sa.Column('power_hp', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('use_trailer', sa.Boolean(), nullable=False),
    sa.CheckConstraint("\n            NULLIF(vin, '') IS NOT NULL\n            OR NULLIF(body_number, '') IS NOT NULL\n            OR NULLIF(chassis_number, '') IS NOT NULL\n            ", name='ck_vehicle_has_identifier'),
    sa.PrimaryKeyConstraint('id'),
    schema='info_api'
    )
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('full_address', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('house', sa.String(length=50), nullable=True),
    sa.Column('building', sa.String(length=50), nullable=True),
    sa.Column('apartment', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['info_api.persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='info_api'
    )
    op.create_table('sts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.Integer(), nullable=False),
    sa.Column('serial', sa.String(length=20), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['info_api.vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='info_api'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sts', schema='info_api')
    op.drop_table('addresses', schema='info_api')
    op.drop_table('vehicles', schema='info_api')
    op.drop_table('persons', schema='info_api')
    op.drop_table('insurance_companies', schema='info_api')
    op.drop_table('drivers', schema='info_api')
    # ### end Alembic commands ###
